### ISSUE TITLE
Is minimist still maintained?

### ISSUE THREAD

**Issue by florianb** [substack/minimist#115]
Hi @substack - since i'm relying on minimist i wonder if this repos is still maintained and if not, i'd like to ask if you need help here?

Best, Florian 🎁

**Comment by alvinsight** [comment]
Well, apparently not ^^

**Comment by jamen** [comment]
A package as simple as this one doesn't need to be maintained for 4+ years.  It establishes a solid implementation then stays unchanged for its users.  I think there are several people who don't want the functionality of this  package to be changed in any big way.

Have you considered forking, doing some of the breaking changes people seem to want, and then publish that instead?  That would personally seem like the better option to me.

**Comment by florianb** [comment]
@jamen there are 33 issued open at the time of writing, even if most of them do not report a bug they need at least some attention.

Even if i would like to introduce breaking changes (i do not) i'm not a fan of "rapidly" forking popular packages since i think in many cases it doesn't serve the community very well quickly adding an unknown alternative.

Currently i am convinced it's a good idea to ask first if you could join the collaborators and help out.

**Comment by laurent22** [comment]
Unfortunately it doesn't look like @substack is still around. Is there any actively maintained fork of this package? I think many people would be interested in it and then all the backlog of pull requests could be handled.

**Comment by alvinsight** [comment]
Hey guys,
Yeah, it looks like @substack has stopped maintaining it, which is a shame for a package with 39.432.822 downloads this month at the time of writing!
If you guys are looking for alternative I switched all my repos to [yargs-parser](https://www.npmjs.com/package/yargs-parser) which is actively maintained and provides the same set of features :)

Just so it doesn't come out wrong, I think it's perfectly fine to stop working on a popular package, `wrench` stopped being maintained and gave us a nice deprecation warning to switch to `fs-extra` and it all worked out.

**Comment by florianb** [comment]
I agree, you can manage dropping the maintenance a lot better. But since i don't know anything about the reasons i'm not blaming anybody.

Thanks for leaving yargs-parser as an alternative.

**Comment by unional** [comment]
GitHub and npm should develop a mitigation plan when the author is not around so that the repository and package can still be maintained in the future without needing to fork and create an alternatively-named package.

**Comment by jamonholmgren** [comment]
It is unfortunate that `minimist` is not maintained. Keep in mind that `yargs-parser`, while actively maintained, is a much larger package, and apparently brings in `yargs` too. If you can get by with minimist, you might consider sticking with that.

![image](https://user-images.githubusercontent.com/1479215/34008971-f59e0e96-e0bb-11e7-89ca-e14709c6e99c.png)

**Comment by alvinsight** [comment]
Hey @jamonholmgren 
Even though `minimist` relies on features that shouldn't change too much in the future, I'd take an increased file size over an unmaintained package that could blow up at any time. 

But I agree with you that such an difference is filesize is not insignificant :)

**Comment by berdon** [comment]
For what it's worth - I've created a rewrite of minimist: [minimist2](https://github.com/berdon/minimist2)

It passes all of minimist's current unit tests but it does target es6. Ymmv but I'll be around to accept pr's, etc.

**Comment by motss** [comment]
Look no further to [meow](https://github.com/sindresorhus/meow), folks. Hope this helps.

**Comment by baruchvlz** [comment]
Question, has anyone tried using [commader.js](https://github.com/tj/commander.js)? Seems to provide all same functionality with a better syntax (in my opinion).

**Comment by dominictarr** [comment]
minimist doesn't need to be maintained. it's totally done. it's perfect.

**Comment by medikoo** [comment]
@dominictarr a friendly reminder ;-)

![image](https://user-images.githubusercontent.com/122434/70786322-b2c36c00-1d8c-11ea-94f7-9a1ff6224263.png)

**Comment by dominictarr** [comment]
software eventually reaches a state where it's so stable that fixing the bugs would break other software. lets call that finished.

**Comment by laurent22** [comment]
> so stable

That doesn't apply to Minimist though. The software is just abandoned, which happens, priorities change, etc. but it's definitely not "finished", let alone bug-free.

**Comment by meszaros-lajos-gyorgy** [comment]
If anyone is reading this, then a few of us have picked up the repo and created a fork, which already has most of the issues sorted. Feel free to check it out: https://github.com/meszaros-lajos-gyorgy/minimist-lite
It have also been published to npm as: https://www.npmjs.com/package/minimist-lite
