### ISSUE TITLE
best way to handle negative numbers?

### ISSUE THREAD

**Issue by hems** [substack/minimist#117]
I'm trying to parse:
````
/something 100 0.1 --my_value -10%
````
considering i know which variables might accept negative numbers i could specify then on the options but i kinda didn't realize how to do it?

any advice on this matter?

thanks a lot

**Comment by barinali** [comment]
If you run `/something --my_value=-10%`, it should be parsed fine.

**Comment by hems** [comment]
thanks, will try it out
