### ISSUE TITLE
Argument of type number with leading zeros causes weird behaviour

### ISSUE THREAD

**Issue by KerimG** [substack/minimist#126]
When I try to pass the following number "00340433950281289025" as a command line argument to my node application, argv looks like this: 

```JavaScript
{ _: [ 340433950281289000 ] }
```

I'm guessing node (or perhaps even minimist) is doing some type casting of sorts. Currently, I'm avoiding that by prepending the parameter with an underscore, which leaves the parameter untouched, and removing it again in my code. 

Is there a more elegant solution to this?

**Comment by QuentinRoy** [comment]
Add `_` in `opts.strings`. That should do it.

**Comment by KerimG** [comment]
Thanks @QuentinRoy  but I moved to Commander, since minimist hasn't been updated in forever.
