### ISSUE TITLE
isNumber()

### ISSUE THREAD

**Issue by bWhirring** [substack/minimist#130]
i hope get "0001" but i got "1" when i execute `node index.js -a "0001"`,  I just want to get what I typed，but you transfered it to a number.

**Comment by bdoner** [comment]
Hi,

Try adding `{"string": "a"}` as an option for the parser.

Example:
``` 
> var parse = require("minimist")
undefined
> parse(["-a", "0001"])
{ _: [], a: 1 }
> parse(["-a", "0001"], {string:"a"})
{ _: [], a: '0001' }
```

**Comment by bWhirring** [comment]
@bdoner thanks, it worked
