### ISSUE TITLE
Error: 405 Method Not Allowed: minimist@1.2.0

### ISSUE THREAD

**Issue by MattRCole** [substack/minimist#131]
While trying to npm install a project, it appears that minimist is causing an error.

Here is a snippit of the log that seems to be pertinent (full log will be included):

    13498 verbose stack Error: 405 Method Not Allowed: minimist@1.2.0
    13498 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
    13498 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    13498 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    13498 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    13498 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    13498 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    13498 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    13498 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    13498 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    13498 verbose stack     at runCallback (timers.js:810:20)
    13498 verbose stack     at tryOnImmediate (timers.js:768:5)
    13498 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
    13499 verbose cwd C:\-------\Vue Source\[app-name] //Edited, sorry about that.
    13500 verbose Windows_NT 6.1.7601
    13501 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    13502 verbose node v8.12.0
    13503 verbose npm  v6.4.1
    13504 error code E405
    13505 error 405 Method Not Allowed: minimist@1.2.0
    13506 verbose exit [ 1, true ]

I am at a loss for what to do. I'm trying to install this onto a windows 7 computer and the project was originally created with vue-cli v3.0.4

Please let me know if there's any more info needed.

[npm-debug-log.txt](https://github.com/substack/minimist/files/2484357/npm-debug-log.txt)

**Comment by goto-bus-stop** [comment]
This is almost certainly an npm issue. minimist does not run any scripts on install so it cannot cause install errors on its own.
