### ISSUE TITLE
Support for shell scripts

### ISSUE THREAD

**Issue by kezike** [substack/minimist#135]
Problem: Recently, I came across an issue while trying to run minimist from a shell script

Example: Consider a JSON utility script that reads keys from and writes key-value pairs to a json file. It takes the following arguments:
```
--json: JSON file being manipulated
--read: whether to read to JSON file
--write: whether to write to JSON file
--delete: whether to delete from JSON file
--key: JSON key
--value: JSON value
```
I have tested this JSON API with lines such as the following:
```
# Write to JSON FILE
node jsonApi.js --write --key=message --value=value --json=jsonFile.json
```
```
# Read from JSON FILE
node jsonApi.js --read --key=message --json=jsonFile.json
```
```
# Delete from JSON FILE
node jsonApi.js --delete --key=message --json=jsonFile.json
```
They seem to behave correctly when run directly on the command line, but when I add them to scripts, it seems that node is mistaking my JSON API's inputs as its own direct inputs. This are some example error messages returned by the script:
```
node: bad option: --write
node: bad option: --key=message
```

Related Issue: #106 

Thanks in advance for your considerate support!

**Comment by nothingismagick** [comment]
@kezike - then you should close this issue. :)

**Comment by kezike** [comment]
Good point, sorry :)
