### ISSUE TITLE
Not all numeric-looking arguments are returned as numbers

### ISSUE THREAD

**Issue by kimbaudi** [substack/minimist#137]
In the README, it clearly states:

> Numeric-looking arguments will be returned as numbers unless `opts.string` or `opts.boolean` is set for that argument name

But this is a lie! Not all numeric-looking arguments (i.e. `-1`) will be returned as numbers. It will be returned as a boolean.

If I parse this argument with minimist

```js
--foo -1
```

minimist will return the following result:

```js
{ '1': true, _: [], foo: true }
```

it looks like minimist is first parsing `-1` as a numeric value, but then later evalutes the value `-1` as a boolean expression (where 0 is false and any other value is true). So -1 becomes true.

**Comment by goto-bus-stop** [comment]
`-1` is parsed as a separate command line flag, similar to what `--foo -k` would be for example. You can use `--foo=-1` instead to force the `-1` to parse as a value.
