### ISSUE TITLE
 1 vulnerability requires manual review. See the full report for details.

### ISSUE THREAD

**Issue by longletian** [substack/minimist#146]
![image](https://user-images.githubusercontent.com/28197668/79069569-e0500000-7d01-11ea-84ad-8f6561309eab.png)

**Comment by Maia-Everett** [comment]
How did you fix this? It still shows up for me, even though my minimist version is updated to 1.2.5.

**Comment by longletian** [comment]
I did not fix it, but this does not seem to affect the use
