### ISSUE TITLE
Open invite to continue maintaining

### ISSUE THREAD

**Issue by p-mcgowan** [substack/minimist#160]
**Edit**: check out [this fork](https://github.com/meszaros-lajos-gyorgy/minimist-lite) which will be even more actively maintained

I think this project is great - it's lightweight, simple, and has just enough features.

Since it doesn't appear to be maintained, I've forked, converted to typescript, added typings, bumped some versions, removed everything prototype related, and closed a few of the issues here in my [fork](https://github.com/p-mcgowan/minimist).

These I would consider resolved
- [substack#94] boolean keys are not defined unless defaulted (can safely spread into other args)
- [substack#123] remove inverted --no-* logic (sets 'no-whatever' = true)
- [substack#154] parse -<opt>=<rest>, where <rest> can contain '=' (-x=asdf=fdsa means `{ x: 'asdf=fdsa' }`

Definitely not backwards compat - `require('minimist')` is now `const { minimist } = require('minimist')`, or `import { minimist } ...`

Additionally, nested dot-separated keys are treated as regular keys - `-foo.bar.baz=10` = `{ 'foo.bar.baz': 10 }`. Open to suggestions, but this appears to be the main source of security issues. From a cli perspective, I don't think it's a commonly used feature, but you can work around it by un-flattening after the parse.

I really only intend to use this myself, but if anyone else wants to contribute or help fix up the issues I would be more than happy.

**Comment by micalevisk** [comment]
sounds great!

ping @substack 

![image](https://user-images.githubusercontent.com/13461315/126723571-b44597fa-a7c0-47c0-b44a-3b81b9be03d6.png)

**Comment by meszaros-lajos-gyorgy** [comment]
And just after releaseing my own fork under the name of minimist-lite I found this github issue. Wanna join forces? My fork is: https://github.com/meszaros-lajos-gyorgy/minimist-lite
https://www.npmjs.com/package/minimist-lite

**Comment by micalevisk** [comment]
@meszaros-lajos-gyorgy nice! could you copy the open issues on this repo to yours? At least the bug reports one

**Comment by meszaros-lajos-gyorgy** [comment]
Yes, I've added a few critical ones already.

**Comment by micalevisk** [comment]
I believe you need to enable them

![image](https://user-images.githubusercontent.com/13461315/146808033-2af89b23-497f-485f-9e4f-2fd25ea9277d.png)

**Comment by meszaros-lajos-gyorgy** [comment]
Ah, sorry, I meant that some fixes from the pull requests were manually copied by me. I've never tried opening parent repo issues in forked repo, I'll check that in a sec.

**Comment by meszaros-lajos-gyorgy** [comment]
I've enabled the issues. Didn't know that it is disabled by default. Can issues from this repo be copied automatically to my fork or does it have to be done manually?

**Comment by p-mcgowan** [comment]
awesome @meszaros-lajos-gyorgy - great minds I suppose.

Admittedly, I only ended up forking, using for my own project, then promptly forgetting about it. I'm happy to contribute to yours too though, better that it's all in one place

**Comment by meszaros-lajos-gyorgy** [comment]
@p-mcgowan If you create a pull request from your fork then I'm happy to merge it, so far I haven't touched the code but instead tried updating the dependencies and added npmignore.

**Comment by p-mcgowan** [comment]
Sounds good, I'll do that - it's typescript though - does that work for you?

**Comment by meszaros-lajos-gyorgy** [comment]
It's generally a good idea to not require the user to have any transpilers to run the code. For example I'm using it for various plain nodejs repos. Can you add a transpiled version of it and make that the default?

**Comment by meszaros-lajos-gyorgy** [comment]
I checked this little tutorial on how to have a typescript package published and typescript is okay, I just need to make sure, that I run tsc before publishing: https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/

**Comment by p-mcgowan** [comment]
Yeah in theory the npm module would be vanilla of course, but that's correct that it would require transpiration to build from source. Personally, I find it's really helpful maintaining other code bases with TS in them as it self documents, but makes sense that it's an extra step for people who don't usually use it.

I can try to open a PR with just the transpiled stuff, I'll have to fiddle with the targets to make it output something close to the original.

**Comment by meszaros-lajos-gyorgy** [comment]
You can add the fully typescript version. Transpilation will be done every time before release and that is the de-facto way of dealing with TS modules.

**Comment by p-mcgowan** [comment]
Sounds good - yeah it should be wired up to build on publush, and I left the tests in js so that shouldn't require a build.
Will try to push something up in the next few days.

**Comment by micalevisk** [comment]
@meszaros-lajos-gyorgy 

> Can issues from this repo be copied automatically to my fork

from what I've searched, no. Unlesse we use GitHub's API to do it programmatically, I guess.

Also, as there are too many issues on this repo, I'd say is better to copy the ones you think you could solve by now. Starting from the most commented ones https://github.com/substack/minimist/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc

<details>
<summary>Here's the GraphQL query that you can use to copy the HTML value of each issue</summary>

https://docs.github.com/graphql/overview/explorer

```graphql
{
  repository(owner: "substack", name: "minimist") {
    issues(first: 100, states: OPEN, orderBy: {field: COMMENTS, direction: DESC}) {
      totalCount
      nodes {
        url
        title
        body
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
```

If you have [GitHub CLI](https://cli.github.com/) installed then you can use:

```bash
gh api graphql --paginate -f query='
{
  repository(owner: "substack", name: "minimist") {
    issues(first: 100, states: OPEN, orderBy: {field: COMMENTS, direction: DESC}) {
      totalCount
      nodes {
        url
        title
        body
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
'
```

along [`jq`](https://stedolan.github.io/jq/) or [`fx`](https://github.com/antonmedv/fx) to process the JSON response

</details>

then you could link the source Issue so users can be aware of your fork :)

**Comment by lucasgonze** [comment]
As a Minimist consumer who needs to patch a vuln, I'd be grateful for a (compatible) fork.

**Comment by meszaros-lajos-gyorgy** [comment]
@lucasgonze please check my fork and feel free to open any tickets for improvements or add some improvements to it yourself via a pull request:
https://github.com/meszaros-lajos-gyorgy/minimist-lite
https://www.npmjs.com/package/minimist-lite

**Comment by meszaros-lajos-gyorgy** [comment]
Hi @p-mcgowan and @micalevisk! I've invited you both as collaborators for the minimist-lite repo! The more people have access the less there is a chance for the project to die off in the future.
