### ISSUE TITLE
Parsing of --no-food as `{food: false}`, is there a way to change that behaviour?.

### ISSUE THREAD

**Issue by fuadop** [substack/minimist#163]

**Comment by micalevisk** [comment]
I don't think so.

What output are you expecting?

**Comment by fuadop** [comment]
> related with #54
> 
> 
> 
> What output are you expecting?
> 
> 
> 
> ---
> 
> 
> 
> btw this repo doesn't appear to be maintained. You can go to this another one https://github.com/meszaros-lajos-gyorgy/minimist-lite

Oh nice 😍. Thanks for the feedback. I was expecting it to be `{'no-colors': true }`. But I had already worked it the the default way, which is the no-flags. 

I would checkout minimist-lite. Thanks once again 💪
