### ISSUE TITLE
Prototype pollution issue still present in 1.2.6

### ISSUE THREAD

**Issue by zackdotcomputer** [substack/minimist#168]
[Snyk has marked release 1.2.6 as still creating a CVE from prototype pollution](https://snyk.io/test/npm/minimist/1.2.6). Unclear how much of an issue this is for CLI usages, but it is surfacing to a lot of users via Angular's use of this package.

**Comment by AlanGreene** [comment]
@zackdotcomputer Snyk has since updated and no longer reports it as vulnerable

**Comment by zackdotcomputer** [comment]
Thanks @AlanGreene for the heads up - marking this as closed 👍
