### ISSUE TITLE
-- option is still parsing remaining args

### ISSUE THREAD

**Issue by H3Chief** [substack/minimist#59]
The docs say that parsing stops after `--`, even when setting `opts[--]` to true. However, I'm getting the args after the `--` back not as a single string, but as an array of args.

path linked cli.js file named 'mycli`:

```js
#!/usr/bin/env node
var parseArgs = require("minimist");

var argv = parseArgs(process.argv.slice(1), {
  '--':true
});

console.log("unparsed input",argv['--']);
```

`$> mycli -- git -v` outputs:
`unparsed input [ 'git', '-v' ]`  

If this isn't parsed, shouldn't it return `unparsed input ['git -v']` ?

**Comment by LongLiveCHIEF** [comment]
here's the entire `argv` object:

`{ _: [ '/usr/local/bin/mycli' ], '--': [ 'git', '-v' ] }`

**Comment by jhenninger** [comment]
No, that has nothing to do with minimist. Your shell will split arguments by spaces and pass them to the binary you are executing. If you want an argument to have spaces you can surround it with quotes:

args.js:
```javscript
console.log(process.argv);
```

```
$ node args.js git -v   
[ 'node', '/tmp/args.js', 'git', '-v' ]
$ node args.js "git -v"
[ 'node', '/tmp/args.js', 'git -v' ]
```

**Comment by H3Chief** [comment]
Yeah, sorry about that. I figured that out soon enough after creating the issue, just couldn't find the issue again to close it.
