### ISSUE TITLE
Passing negative numbers results in true

### ISSUE THREAD

**Issue by nodesocket** [substack/minimist#82]
This should not be the behavior, it should pass negative numbers along.

````javascript
# test.js file
const args = require('minimist')(process.argv.slice(2));
console.log(args.input)
````

````shell
node test.js --input -34
true
````

Even quoting does not help:

````shell
node test.js --input "-34"
true
````

**Comment by rsp** [comment]
The way minimist works in this case is consistent with the usual conventions. You run `head -2` to print two lines. The same is with `tail` and other commends. The `"-"` is not part of the number but a prefix of the option that just happens to be a digit.

Similarly, I wouldn't expect this:
`node test.js --input -x`
to put `"-x"` as the value of `input`.

Even programs that don't have numeric options still interpret them this way:
`$ ping -2`
`ping: invalid option -- '2'`

What you are trying to do can be achieved by:
`node test.js --input=-34`

**Comment by nodesocket** [comment]
Ahhh, makes sense using `--input=-34`.
