### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jviotti** [substack/minimist#83]
The last commit is on [August 29th, 2015](https://github.com/substack/minimist/commits/master), there are [20 opened issues](https://github.com/substack/minimist/issues) and [18 opened pull requests](https://github.com/substack/minimist/pulls), most of them without even a comment.

@substack I see that you're quite active on GitHub, and understand that you might be very busy with other projects. If so, can you pass the ownership to a new maintainer, or give access to collaborators so that this project doesn't rot? Its a pity to let such a nice and useful project slowly die.

**Comment by lipis** [comment]
There is nothing wrong with dead projects.. but it would be nice to know.. maybe update the readme as well.

**Comment by klamping** [comment]
I'm guessing so. Check out https://github.com/yargs/yargs-parser for a more modern tool.
