### ISSUE TITLE
Suggestion: single-line ES2015 import style

### ISSUE THREAD

**Issue by callumlocke** [substack/minimist#99]
Currently it feels a little messy using minimist with ES2015 imports, as you can't do a curried require so you have to add an extra line after your imports.

It would be cool if you could do it in one statement instead:

``` js
import argv from 'minimist/load';
```

For this to work, all that's needed is a file called `load.js` which contains `module.exports = require('.')(process.argv.slice(2));`.

Happy to PR if interested.

**Comment by PixsaOJ** [comment]
How would you do this today? I have `import argv from 'minimist';` then `argv(process.argv.slice(2), {default :....}` but it does not work
